[package]
name = "esm"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.10.0"
flate2 = { version = "1.1.1", features = ["cloudflare_zlib"] }
glam = { version = "0.30.9", features = ["bytemuck", "zerocopy"] }
gltf = { version = "1.4.1", features = ["extensions", "KHR_materials_pbrSpecularGlossiness"] }
nom-derive = "0.10.1"
proc = { path = "../proc" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
