[workspace]
resolver = "2"
members = [ "app","ba2", "cli", "editor", "esm", "gen", "nif", "proc", "shared"]


# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
