[package]
name = "project-wormhole-ba2"
version = "0.1.0"
edition = "2021"
description = "BA2 file format parser for Project Wormhole"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0.28", features = ["cloudflare_zlib"] }
log = "0.4.20"
nom-derive = "0.10.1"
image_dds = "0.4.0"
image = "0.24.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"


project-wormhole-shared = { path = "../shared", version = "0.1.0"  }
