[package]
name = "editor"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Editor application for Project Wormhole"


[dependencies]
bevy = "0.17.3"
bevy_hui = "0.5.0"

project-wormhole-shared = { path = "../shared" }
project-wormhole-esm = { path = "../esm" }
project-wormhole-bgsm = { path = "../bgsm" }
project-wormhole-nif = { path = "../nif" }
project-wormhole-ba2 = { path = "../ba2" }
bevy_aseprite_ultra = "0.7.0"
rand = "0.9.2"

