[package]
name = "project-wormhole-es"
version = "0.1.0"
edition = "2024"
description = "ESM file format parser for Project Wormhole"
license = "GPL-3.0-or-later"
keywords = ["esm", "bethesda", "esp", "fallout"]

[dependencies]
bitflags = "2.10.0"
comfy-table = "7.2.2"
flate2 = { version = "1.1.1", features = ["cloudflare_zlib"] }
glam = { version = "0.30.9", features = ["bytemuck", "zerocopy"] }
gltf = { version = "1.4.1", features = ["extensions", "KHR_materials_pbrSpecularGlossiness"] }
nom-derive = "0.10.1"
project-wormhole-proc = { path = "../proc", version = "0.1.0" }
project-wormhole-shared = { path = "../shared", version = "0.1.0" }
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
speedy = { version = "0.8.7", optional = true }