[package]
name = "project-wormhole-shared"
version = "0.1.0"
edition = "2024"
description = "Shared utilities and types for Project Wormhole"
license = "GPL-3.0-or-later"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
glam = { version = "0.30.9", features = ["bytemuck", "zerocopy"] }
nom-derive = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
speedy = "0.8.7"
zerocopy = { version = "0.8.31", features = ["derive"] }
