[package]
name = "project-wormhole-bgsm"
version = "0.1.0"
edition = "2024"
description = "BGSM file format parser for Project Wormhole"
license = "GPL-3.0-or-later"
keywords = ["bgsm", "bethesda", "material", "fallout"]

[dependencies]
nom-derive = "0.10.1"

project-wormhole-shared = { path = "../shared", version = "0.1.0"  }